  eval_webnlg:
    dataset: webnlg
    split: eval
    fairseq_gpt2:
      gpt2_encoder_json: encoder.json
      gpt2_vocab_bpe: vocab.bpe
    sentenpiece:
      sentencepiece_model: sentence.bpe.model
    kgpt_gpt2:
      tokenizer_dir: GPT2_tokenizer
    option: eval
    tokenizer_src: kgpt_gpt2
    tokenizer_tgt: kgpt_gpt2
    vocab_file_src: "dict.gpt2.txt"
    vocab_file_tgt: "dict.gpt2.txt"
    src_lang: "en_XX"
    tgt_lang: "en_XX"
    tgt_lang_tag_template: "[{}]"
    src_lang_tag_template: "[{}]"
    prepend_src_lang_tag: False
    prepend_tgt_lang_tag: False
    src_wtags: True
    tgt_wtags: True
    train_file: train.json
    test_file: test.json
    eval_file: eval.json
    encoder_arch: sequence
    percent: 1.0
    src_length: 256
    tgt_length: 72
    max_fact: 8
    max_entity: 12
    num_workers: 8
    batch_size: 64
